# Generated by Django 3.2.5 on 2021-07-28 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='pic',
            field=models.TextField(),
        ),
    ]
